@startuml


component jackson {
}

component core {
	package casflow.core
	package casflow.json
}

casflow.core ..> casflow.json
casflow.json ..> jackson

component ui {
	package casflow.ui
}

casflow.ui ..> casflow.core
casflow.ui ..> casflow.json

component javafx {
	component fxml {
	}
}

ui ..> javafx
ui ..> fxml

@enduml
