@startuml
actor User
User -> "~#createAccount: Button" as createAccount: click
createAccount -> CashFlowController: onCreateAccount
CashFlowController -> Core: getAccountFromType
CashFlowController <- Core: account
CashFlowController -> RestAPI: addAccount PUT-request
RestAPI -> Core: response
CashFlowController -> Core: user.addAccount
CashFlowController -> User: setText
@enduml
